Watching for file changes with StatReloader
Waiting for apps ready_event.
Apps ready_event triggered. Sending autoreload_started signal.
Watching dir C:\Users\HP\Desktop\project_1\complaint_system\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\admin\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\auth\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\contenttypes\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\sessions\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\messages\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\staticfiles\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\rest_framework\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\complaint_system\users\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\complaint_system\complaint\locale with glob **/*.mo.
(0.002) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.001) SHOW FULL TABLES; args=None
(0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
Watching for file changes with StatReloader
Waiting for apps ready_event.
Apps ready_event triggered. Sending autoreload_started signal.
Watching dir C:\Users\HP\Desktop\project_1\complaint_system\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\admin\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\auth\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\contenttypes\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\sessions\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\messages\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\staticfiles\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\rest_framework\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\complaint_system\users\locale with glob **/*.mo.
Watching dir C:\Users\HP\Desktop\project_1\complaint_system\complaint\locale with glob **/*.mo.
(0.064) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.177) SHOW FULL TABLES; args=None
(0.067) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
INFO Watching for file changes with StatReloader
DEBUG Waiting for apps ready_event.
DEBUG Apps ready_event triggered. Sending autoreload_started signal.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\admin\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\auth\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\contenttypes\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\sessions\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\messages\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\staticfiles\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\rest_framework\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\users\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\complaint\locale with glob **/*.mo.
DEBUG (0.018) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.017) SHOW FULL TABLES; args=None
DEBUG (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
INFO "GET /api/complaint/1 HTTP/1.1" 301 0
INFO "GET /api/complaint/10 HTTP/1.1" 301 0
DEBUG (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.566) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2021-03-28 10:59:01.378442' AND `django_session`.`session_key` = 'za2fx57c2z390ajqljxxhdekcq3nnics'); args=('2021-03-28 10:59:01.378442', 'za2fx57c2z390ajqljxxhdekcq3nnics')
DEBUG (0.069) SELECT `users_user`.`id`, `users_user`.`password`, `users_user`.`last_login`, `users_user`.`email`, `users_user`.`username`, `users_user`.`is_admin`, `users_user`.`is_active`, `users_user`.`is_staff`, `users_user`.`is_superuser` FROM `users_user` WHERE `users_user`.`id` = 1; args=(1,)
DEBUG (0.058) SELECT `complaint_complaint`.`id`, `complaint_complaint`.`title`, `complaint_complaint`.`description`, `complaint_complaint`.`image` FROM `complaint_complaint` WHERE `complaint_complaint`.`id` = 1; args=(1,)
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG (1.087) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2021-03-28 10:59:01.376437' AND `django_session`.`session_key` = 'za2fx57c2z390ajqljxxhdekcq3nnics'); args=('2021-03-28 10:59:01.376437', 'za2fx57c2z390ajqljxxhdekcq3nnics')
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG (0.034) SELECT `users_user`.`id`, `users_user`.`password`, `users_user`.`last_login`, `users_user`.`email`, `users_user`.`username`, `users_user`.`is_admin`, `users_user`.`is_active`, `users_user`.`is_staff`, `users_user`.`is_superuser` FROM `users_user` WHERE `users_user`.`id` = 1; args=(1,)
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG (0.002) SELECT `complaint_complaint`.`id`, `complaint_complaint`.`title`, `complaint_complaint`.`description`, `complaint_complaint`.`image` FROM `complaint_complaint` WHERE `complaint_complaint`.`id` = 10; args=(10,)
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1837E748>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE183D1D68>}
INFO "GET /api/complaint/1/ HTTP/1.1" 200 10705
INFO "GET /api/complaint/10/ HTTP/1.1" 200 10762
ERROR "GET /api/complaint/1/ HTTP/1.1" 500 59
INFO "GET /api/complaint/20 HTTP/1.1" 301 0
DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2021-03-28 10:59:12.927821' AND `django_session`.`session_key` = 'za2fx57c2z390ajqljxxhdekcq3nnics'); args=('2021-03-28 10:59:12.927821', 'za2fx57c2z390ajqljxxhdekcq3nnics')
DEBUG (0.000) SELECT `users_user`.`id`, `users_user`.`password`, `users_user`.`last_login`, `users_user`.`email`, `users_user`.`username`, `users_user`.`is_admin`, `users_user`.`is_active`, `users_user`.`is_staff`, `users_user`.`is_superuser` FROM `users_user` WHERE `users_user`.`id` = 1; args=(1,)
DEBUG (0.000) SELECT `complaint_complaint`.`id`, `complaint_complaint`.`title`, `complaint_complaint`.`description`, `complaint_complaint`.`image` FROM `complaint_complaint` WHERE `complaint_complaint`.`id` = 20; args=(20,)
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001BE1834D240>}
WARNING Not Found: /api/complaint/20/
WARNING "GET /api/complaint/20/ HTTP/1.1" 404 10377
INFO Watching for file changes with StatReloader
DEBUG Waiting for apps ready_event.
DEBUG Apps ready_event triggered. Sending autoreload_started signal.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\admin\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\auth\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\contenttypes\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\sessions\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\messages\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\staticfiles\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\rest_framework\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\users\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\complaint\locale with glob **/*.mo.
DEBUG (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.049) SHOW FULL TABLES; args=None
DEBUG (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2021-03-28 11:00:43.752670' AND `django_session`.`session_key` = 'za2fx57c2z390ajqljxxhdekcq3nnics'); args=('2021-03-28 11:00:43.752670', 'za2fx57c2z390ajqljxxhdekcq3nnics')
DEBUG (0.001) SELECT `users_user`.`id`, `users_user`.`password`, `users_user`.`last_login`, `users_user`.`email`, `users_user`.`username`, `users_user`.`is_admin`, `users_user`.`is_active`, `users_user`.`is_staff`, `users_user`.`is_superuser` FROM `users_user` WHERE `users_user`.`id` = 1; args=(1,)
DEBUG (0.001) SELECT `complaint_complaint`.`id`, `complaint_complaint`.`title`, `complaint_complaint`.`description`, `complaint_complaint`.`image` FROM `complaint_complaint` WHERE `complaint_complaint`.`id` = 20; args=(20,)
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C08E828>}
WARNING Not Found: /api/complaint/20/
WARNING "GET /api/complaint/20/ HTTP/1.1" 404 10377
INFO "GET /api/complaint/3 HTTP/1.1" 301 0
DEBUG (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2021-03-28 11:01:12.559335' AND `django_session`.`session_key` = 'za2fx57c2z390ajqljxxhdekcq3nnics'); args=('2021-03-28 11:01:12.559335', 'za2fx57c2z390ajqljxxhdekcq3nnics')
DEBUG (0.000) SELECT `users_user`.`id`, `users_user`.`password`, `users_user`.`last_login`, `users_user`.`email`, `users_user`.`username`, `users_user`.`is_admin`, `users_user`.`is_active`, `users_user`.`is_staff`, `users_user`.`is_superuser` FROM `users_user` WHERE `users_user`.`id` = 1; args=(1,)
DEBUG (0.001) SELECT `complaint_complaint`.`id`, `complaint_complaint`.`title`, `complaint_complaint`.`description`, `complaint_complaint`.`image` FROM `complaint_complaint` WHERE `complaint_complaint`.`id` = 3; args=(3,)
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000021C8C02DBA8>}
INFO "GET /api/complaint/3/ HTTP/1.1" 200 10764
DEBUG File C:\Users\HP\Desktop\project_1\complaint_system\complaint\api\views.py. is_changed: False, is_new: True
DEBUG File C:\Users\HP\Desktop\project_1\complaint_system\complaint\api\views.py previous mtime: None, current mtime: 1616929730.9506822
DEBUG C:\Users\HP\Desktop\project_1\complaint_system\complaint\api\views.py notified as changed. Signal results: [(<function translation_file_changed at 0x0000021C8B9E6510>, None)].
INFO C:\Users\HP\Desktop\project_1\complaint_system\complaint\api\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Waiting for apps ready_event.
DEBUG Apps ready_event triggered. Sending autoreload_started signal.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\admin\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\auth\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\contenttypes\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\sessions\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\messages\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\contrib\staticfiles\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\env\lib\site-packages\rest_framework\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\users\locale with glob **/*.mo.
DEBUG Watching dir C:\Users\HP\Desktop\project_1\complaint_system\complaint\locale with glob **/*.mo.
DEBUG (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.001) SHOW FULL TABLES; args=None
DEBUG (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
INFO "GET /api/complaint/50 HTTP/1.1" 301 0
DEBUG (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2021-03-28 11:08:59.029087' AND `django_session`.`session_key` = 'za2fx57c2z390ajqljxxhdekcq3nnics'); args=('2021-03-28 11:08:59.029087', 'za2fx57c2z390ajqljxxhdekcq3nnics')
DEBUG (0.001) SELECT `users_user`.`id`, `users_user`.`password`, `users_user`.`last_login`, `users_user`.`email`, `users_user`.`username`, `users_user`.`is_admin`, `users_user`.`is_active`, `users_user`.`is_staff`, `users_user`.`is_superuser` FROM `users_user` WHERE `users_user`.`id` = 1; args=(1,)
DEBUG (0.001) SELECT `complaint_complaint`.`id`, `complaint_complaint`.`title`, `complaint_complaint`.`description`, `complaint_complaint`.`image` FROM `complaint_complaint` WHERE `complaint_complaint`.`id` = 50; args=(50,)
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
DEBUG Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\project_1\env\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in {'base_template': 'input.html', 'input_type': 'file', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000185A9D6B5F8>}
WARNING Not Found: /api/complaint/50/
WARNING "GET /api/complaint/50/ HTTP/1.1" 404 10377
